DEFAULT_BROKER_SERVERS = ['localhost:9092']
DEFAULT_TOPIC='recommendation-requests'
DEFAULT_NUMBER_OF_MESSAGES = 240_000
DEFAULT_NUMBER_OF_GENERATORS = 5
DEFAULT_TIME_IN_SECS = 120
DEFAULT_WAIT_TIME_IN_SECS = 180
